name: Rust

on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]
        include:
        # Allow failures on nightly
        - rust: nightly
          can-fail: true
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies
      run: sudo apt-get install libdbus-1-dev
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@main
    - name: Run Tests
      run: cargo test --verbose
      continue-on-error: ${{ matrix.can-fail }}
